## Initiation from here
#### Video 1
##### https://www.youtube.com/playlist?list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK

In [22]:
import numpy as np

list1 = [1,2,3, 4, 5]

print(list1)
print(list1[0])

list2 = ["john Elder", 41,[1,2,3,4]]
print(list2)

# Numpy - Numeric python
# ndarry = n-dimensional array

np1 = np.array([0,1,2,3,4,5,6,7,8,9])

print(np1)
print(np1.shape)

np2 = np.arange(10)
print(np2)

np3 = np.arange(0,10,2)
print(np3)

np4 = np.zeros(10)
print(np4)

np5 = np.zeros((2,10))
print(np5)

np6 = np.full((10), 6)
print(np6)

np7 = np.full((2,10), 6)
print(np7)

# conver python list to numpy
my_list = [1,2,3,4,5,6]
np8 = np.array(my_list)
print(np8)
print(np8[0])

[1, 2, 3, 4, 5]
1
['john Elder', 41, [1, 2, 3, 4]]
[0 1 2 3 4 5 6 7 8 9]
(10,)
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[6 6 6 6 6 6 6 6 6 6]
[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]
[1 2 3 4 5 6]
1


### Video 2

In [34]:
import numpy as np

np1 = np.array([1,2,3,4,5,6,7,8,9])

# Return 2,3,4,5

print(np1[1:5])
print(np1[1:])
print(np1[:4])
print(np1[-3:-1])

# steps
print(np1[1:5:2])

print(np1[::3])

np2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# Slice a 2-d array

print(np2[1,2])
print(np2[0:1, 1:3])
print(np2[0:2, 1:3])






[2 3 4 5]
[2 3 4 5 6 7 8 9]
[1 2 3 4]
[7 8]
[2 4]
[1 4 7]
8
[[2 3]]
[[2 3]
 [7 8]]


### Video 3

In [40]:
import numpy as np


np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
# Square root of each element

print(np.sqrt(np1))

# absolute value 
np2 = np.array([-3,-2,-1,0,1,2,3,4,5])
print(np.absolute(np2))

print(np.exp(np1))
print(np.max(np1))
print(np.min(np1))

# Sing positive or negative
print(np.sign(np1))
print(np.sign(np2))

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[3 2 1 0 1 2 3 4 5]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
9
0
[0 1 1 1 1 1 1 1 1 1]
[-1 -1 -1  0  1  1  1  1  1]


### Video 4

In [43]:
import numpy as np

# copy vs view
np1 = np.array([0,1,2,3,4,5,6,7])

# Create a view
np2 = np1.view()
print(f'Original np1 {np1}')
print(f'Original np2 {np2}')

np1[0] = 41

print(f'Changed Original np1 {np1}')
print(f'Changed Original np2 {np2}')


# Create a copy
np3 = np.array([0,1,2,3,4,5,6,7])
np4 = np3.copy()
print(f'Original np3 {np3}')
print(f'Original np5 {np4}')

np3[0] = 41

print(f'Original np3 {np3}')
print(f'Original np5 {np4}')

Original np1 [0 1 2 3 4 5 6 7]
Original np2 [0 1 2 3 4 5 6 7]
Changed Original np1 [41  1  2  3  4  5  6  7]
Changed Original np2 [41  1  2  3  4  5  6  7]
Original np3 [0 1 2 3 4 5 6 7]
Original np5 [0 1 2 3 4 5 6 7]
Original np3 [41  1  2  3  4  5  6  7]
Original np5 [0 1 2 3 4 5 6 7]


### Video 5

In [52]:
# Create 1-D Numpy Array and Get Shape
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1.shape)



# Create 2-D Numpy Array and Get Shape

np2 = np.array([
    [1,2,3,4,5,6],
    [7,8,9,10,11,12]])
print(np2.shape)

# Reshape 2-D
np3 = np1.reshape(3,4)
print(np3)
print(np3.shape)

# Reshape 3-D
np4 = np1.reshape(2,3,2)
print(np4.shape)
print(np4)

# Reshape 1-D
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

(12,)
(2, 6)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


### Video 6

In [62]:
import numpy as np

np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

for x in np1:
    print(x, end="")

print()

# 2-D Array
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

for x in np2:
    for y in x:
        print(y)
    
# 3-D Array
np3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(np3.shape)

# Use np.nditer()

# for x in np.nditer(np3):
#     print(x)
# for x in np.nditer(np2):
#     print(x)



123456789101112
1
2
3
4
5
6
7
8
9
10
(2, 2, 3)


### Video 7

In [68]:
import numpy as np

np1 = np.array([1,2,3,4,5,10,6,7,8,9])
print(np1)

# number sort
print(np.sort(np1))

# Alphabatic Sort
np2 = np.array(["John", "Tina", "Aron"])
print(np.sort(np2))

# Boolens T/F
np3 = np.array([True, False, False, True])

print(np.sort(np3))


# Return a copy not change the original
np4 = np.array([[1,2,4,3,5],[6,7,9,8,10]])
print(np.sort(np4))

[ 1  2  3  4  5 10  6  7  8  9]
[ 1  2  3  4  5  6  7  8  9 10]
['Aron' 'John' 'Tina']
[False False  True  True]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Video 8

In [73]:
import numpy as np

np1 = np.array([1,2,3,4,5,6,7,8,9])

x = np.where(np1 == 3)
print(np1)
print(x[0])
print(np1[[x[0]]])


# Order even number
y = np.where(np1%2 == 0)

print(y)
print(np1[y[0]])

# return odd number



[1 2 3 4 5 6 7 8 9]
[2]
[[3]]
(array([1, 3, 5, 7]),)
[2 4 6 8]


### Video 9

In [1]:
import numpy as np

# Filtering numpy array With Boolen index
np1 = np.array([1,2,3,4,5,6,7,8,9])

x = [True, True, False, False, False, False, False, False, False]

print(np1)
print(np1[x])

[1 2 3 4 5 6 7 8 9]
[1 2]
